stages:
  - nonprod
  - preprod
  - prod

nonprod:ansible-test:
  stage: nonprod
  tags:
    - nonprod
  image: ansible/centos7-ansible
  script:
    - echo "hello nonprod"


preprod:ansible-test:
  stage: preprod
  tags:
    - preprod
  image: ansible/centos7-ansible
  script:
    - echo "hello preprod"


prod:ansible-test:
  stage: prod
  tags:
    - prod
  image: ansible/centos7-ansible
  script:
    - echo "hello prod"