stages:
  - nonprod
  - preprod
  - prod

nonprod:ansible-test:
  stage: nonprod
  variables:
    DEPLOY_ENV: ansible/nonprod
  tags:
    - nonprod
  image: ansible/centos7-ansible
  script:
    - rm -rf /etc/yum.repos.d/*
    - mv ansible/test.repo  /etc/yum.repos.d/
    - yum clean all
    - yum install  sshpass -y
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
    - mv  ansible/hosts  /etc/ansible/hosts
    - mv  ansible/ansible.cfg  /etc/ansible/ansible.cfg
    - cp -r  ${DEPLOY_ENV}  /var/local
    - sh build/build.sh
    - cp common/target/common-1.0-SNAPSHOT.jar /var/local
    - ansible-playbook  --vault-password-file ansible/pwdfile ${DEPLOY_ENV}/flink.yml  -e "cluster=data"    --limit   nonprod-flink

nonprod:ansible-apply:
  stage: nonprod
  when: manual
  variables:
    DEPLOY_ENV: ansible/nonprod
  tags:
    - nonprod
  image: ansible/centos7-ansible
  script:
    - rm -rf /etc/yum.repos.d/*
    - mv ansible/test.repo  /etc/yum.repos.d/
    - yum clean all
    - yum install  sshpass -y
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
    - mv  ansible/hosts  /etc/ansible/hosts
    - mv  ansible/ansible.cfg  /etc/ansible/ansible.cfg
    - cp -r  ${DEPLOY_ENV}  /var/local
    - sh build/build.sh
    - cp common/target/common-1.0-SNAPSHOT.jar /var/local
    - ansible-playbook  --vault-password-file ansible/pwdfile ${DEPLOY_ENV}/flink.yml  -e "cluster=data"    --limit   nonprod-flink

preprod:ansible-test:
  stage: preprod
  tags:
    - preprod
  image: ansible/centos7-ansible
  script:
    - echo "hello preprod"


prod:ansible-test:
  stage: prod
  tags:
    - prod
  image: ansible/centos7-ansible
  script:
    - echo "hello prod"